apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ingest.fullname" . }}-logstash-init-script
data:
  logstash-init.sh: | 
    #!/bin/bash
    # Logstash init script
  
    set -x
    # Get mitre_attack.csv from HELK and copy it to the Logstash volume
    # https://github.com/Cyb3rWard0g/HELK
    yum install -y git
    git clone https://github.com/Cyb3rWard0g/HELK.git
    cd HELK/helk-logstash/enrichments/cti/
    cp mitre_attack.csv /attack-csv/
  